# Generated by Django 3.1.6 on 2021-03-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210317_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
